name: Jam Test Vectors

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-vectors:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jam_version: [ '0.7.2' ]

    env:
      BIN_ARCH: x86-64
      JAM_VERSION: ${{ matrix.jam_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Jampy
        uses: ./.github/actions/setup-jampy
        with:
          jam_version: ${{ env.JAM_VERSION }}

      - name: Install git
        run: sudo apt-get install -y git

      - name: Clone jam-test-vectors
        run: git clone https://github.com/davxy/jam-test-vectors

      - name: Run fuzzer on traces - fallback
        run: |
          cd ./jampy-fuzzer/jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }}/
          for f in ${{ github.workspace }}/jam-test-vectors/traces/fallback/*.bin; do
            if [[ "$f" != *genesis* ]]; then
              echo "Running fuzzer on $f"
              ./jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }} --socket-file ${{ github.workspace }}/jam_target.sock --single-trace "$f"
            fi
          done

      - name: Run fuzzer on traces - safrole
        run: |
          cd ./jampy-fuzzer/jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }}/
          for f in ${{ github.workspace }}/jam-test-vectors/traces/safrole/*.bin; do
            if [[ "$f" != *genesis* ]]; then
              echo "Running fuzzer on $f"
              ./jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }} --socket-file ${{ github.workspace }}/jam_target.sock --single-trace "$f"
            fi
          done

      - name: Run fuzzer on traces - preimages_light
        run: |
          cd ./jampy-fuzzer/jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }}/
          for f in ${{ github.workspace }}/jam-test-vectors/traces/preimages_light/*.bin; do
            if [[ "$f" != *genesis* ]]; then
              echo "Running fuzzer on $f"
              ./jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }} --socket-file ${{ github.workspace }}/jam_target.sock --single-trace "$f"
            fi
          done

      - name: Run fuzzer on traces - storage_light
        run: |
          cd ./jampy-fuzzer/jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }}/
          for f in ${{ github.workspace }}/jam-test-vectors/traces/storage_light/*.bin; do
            if [[ "$f" != *genesis* ]]; then
              echo "Running fuzzer on $f"
              ./jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }} --socket-file ${{ github.workspace }}/jam_target.sock --single-trace "$f"
            fi
          done

      - name: Run fuzzer on traces - fuzzy_light
        run: |
          cd ./jampy-fuzzer/jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }}/
          for f in ${{ github.workspace }}/jam-test-vectors/traces/fuzzy_light/*.bin; do
            if [[ "$f" != *genesis* ]]; then
              echo "Running fuzzer on $f"
              ./jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }} --socket-file ${{ github.workspace }}/jam_target.sock --single-trace "$f"
            fi
          done

      - name: Run fuzzer on traces - preimages
        run: |
          cd ./jampy-fuzzer/jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }}/
          for f in ${{ github.workspace }}/jam-test-vectors/traces/preimages/*.bin; do
            if [[ "$f" != *genesis* ]]; then
              echo "Running fuzzer on $f"
              ./jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }} --socket-file ${{ github.workspace }}/jam_target.sock --single-trace "$f"
            fi
          done

      - name: Run fuzzer on traces - storage
        run: |
          cd ./jampy-fuzzer/jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }}/
          for f in ${{ github.workspace }}/jam-test-vectors/traces/storage/*.bin; do
            if [[ "$f" != *genesis* ]]; then
              echo "Running fuzzer on $f"
              ./jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }} --socket-file ${{ github.workspace }}/jam_target.sock --single-trace "$f"
            fi
          done

      - name: Run fuzzer on traces - fuzzy
        run: |
          cd ./jampy-fuzzer/jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }}/
          for f in ${{ github.workspace }}/jam-test-vectors/traces/fuzzy/*.bin; do
            if [[ "$f" != *genesis* ]]; then
              echo "Running fuzzer on $f"
              ./jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }} --socket-file ${{ github.workspace }}/jam_target.sock --single-trace "$f"
            fi
          done

      - name: Stop jampy-target
        if: always()
        run: |
          kill $(cat target.pid) 2>/dev/null || true
          rm -f ${{ github.workspace }}/jam_target.sock
