name: MiniFuzz

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  JAM_VERSION: 0.7.2
  BIN_ARCH: x86-64

jobs:
  test-vectors:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jam_version: [ '0.7.0', '0.7.1', '0.7.2' ]

    env:
      BIN_ARCH: x86-64
      JAM_VERSION: ${{ matrix.jam_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install unzip git
        run: sudo apt-get update && sudo apt-get install -y unzip git

      - name: Extract jampy-target
        run: unzip -q dist/jampy-target-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }}.zip -d jampy-target

      - name: Extract jampy-fuzzer
        run: unzip -q dist/jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }}.zip -d jampy-fuzzer

      - name: Make binaries executable
        run: |
          chmod +x jampy-target/jampy-target-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }}/jampy-target-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }}
          chmod +x jampy-fuzzer/jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }}/jampy-fuzzer-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }}

      - name: Install jam-types-py
        run: |
          export GITHUB_REF=refs/tags/v${{ env.JAM_VERSION }}
          pip install https://github.com/davxy/jam-types-py/archive/refs/tags/v${{ env.JAM_VERSION }}.tar.gz

      - name: Clone jam-conformance
        run: git clone https://github.com/davxy/jam-conformance

      - name: Run jampy-target in background
        run: |
          ./jampy-target/jampy-target-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }}/jampy-target-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }} &
          echo $! > target.pid
        shell: bash

      - name: Wait for target startup
        run: sleep 5

      - name: Run fuzzer on minifuzz examples - no_forks
        run: |
          python jam-conformance/fuzz-proto/minifuzz/minifuzz.py -d jam-conformance/fuzz-proto/examples/0.7.2/no_forks

      - name: Run fuzzer on minifuzz examples - forks
        run: |
          python jam-conformance/fuzz-proto/minifuzz/minifuzz.py -d jam-conformance/fuzz-proto/examples/0.7.2/forks

      - name: Stop jampy-target
        if: always()
        run: kill $(cat target.pid)
