name: MiniFuzz

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-vectors:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - jam_version: '0.7.2'
            flags: ''
          - jam_version: '0.7.2'
            flags: '--use-recompiler'

    env:
      BIN_ARCH: x86-64
      JAM_VERSION: ${{ matrix.jam_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Jampy
        uses: ./.github/actions/setup-jampy
        with:
          jam_version: ${{ env.JAM_VERSION }}

      - name: Install git
        run: sudo apt-get install -y git

      - name: Install jam-types-py
        run: |
          export GITHUB_REF=refs/tags/v${{ env.JAM_VERSION }}
          pip install https://github.com/davxy/jam-types-py/archive/refs/tags/v${{ env.JAM_VERSION }}.tar.gz --break-system-packages

      - name: Clone jam-conformance
        run: git clone https://github.com/davxy/jam-conformance

      - name: Start jampy-target
        run: |
          cd ./jampy-target/jampy-target-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }}/
          nohup ./jampy-target-${{ env.JAM_VERSION }}_${{ env.BIN_ARCH }} ${{ matrix.flags }} --socket-file ${{ github.workspace }}/jam_target.sock > ${{ github.workspace }}/target.log 2>&1 &
          echo $! > ${{ github.workspace }}/target.pid
          sleep 3
          for i in 1 2 3 4 5; do
            [ -S ${{ github.workspace }}/jam_target.sock ] && echo "Socket ready" && exit 0
            sleep 1
          done
          echo "Socket not found"
          cat ${{ github.workspace }}/target.log
          exit 1

      - name: Run fuzzer on minifuzz examples - no_forks
        run: |
          python jam-conformance/fuzz-proto/minifuzz/minifuzz.py -d jam-conformance/fuzz-proto/examples/${{ env.JAM_VERSION }}/no_forks --target-sock  ${{ github.workspace }}/jam_target.sock

      - name: Run fuzzer on minifuzz examples - forks
        run: |
          python jam-conformance/fuzz-proto/minifuzz/minifuzz.py -d jam-conformance/fuzz-proto/examples/${{ env.JAM_VERSION }}/forks --target-sock  ${{ github.workspace }}/jam_target.sock

      - name: Stop jampy-target
        if: always()
        run: |
          kill $(cat target.pid) 2>/dev/null || true
          rm -f ${{ github.workspace }}/jam_target.sock
